#!/usr/bin/env python
"""Run the full pre-registered statistical analysis across all four configurations.

Usage:
    uv run scripts/run_stats.py

Reads:
    reports/base_results.jsonl
    reports/rag_results.jsonl
    reports/ft_results.jsonl
    reports/ft_rag_results.jsonl

Writes:
    reports/full_comparison.md        — main Phase 4 report (all 5 contrasts)
    reports/forest_C{1..5}.png        — forest plot per pre-registered contrast
    reports/base_vs_rag.md            — kept for backward compatibility (C1 only)
    reports/base_vs_rag_forest.png    — regenerated from the joint Holm correction
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from ragbench.eval.reporting import forest_plot, write_report
from ragbench.eval.stats import analyse

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# Pre-registered contrasts (EXPERIMENT.md §7) — all five tested together so
# Holm–Bonferroni is applied jointly across 5 p-values per metric.
CONTRASTS: list[tuple[str, str]] = [
    ("base", "rag"),  # C1
    ("base", "ft"),  # C2
    ("base", "ft_rag"),  # C3
    ("ft", "ft_rag"),  # C4
    ("rag", "ft_rag"),  # C5
]
CONFIGS = ["base", "rag", "ft", "ft_rag"]
METRICS = ["exact_match", "token_f1"]
RAG_CONFIGS = ["rag", "ft_rag"]  # configs that have faithfulness scores


def load_jsonl(path: Path) -> list[dict]:
    with open(path) as f:
        return [json.loads(line) for line in f if line.strip()]


def align_all(
    config_rows: dict[str, list[dict]],
    metrics: list[str],
) -> dict[str, dict[str, np.ndarray]]:
    """Align multiple configs by question ID and return metric arrays.

    All configs must cover identical question IDs; otherwise raises ValueError.
    Array order follows the first config's row order.
    """
    indexed = {cfg: {r["id"]: r for r in rows} for cfg, rows in config_rows.items()}

    id_sets = {cfg: set(idx.keys()) for cfg, idx in indexed.items()}
    reference_ids = next(iter(id_sets.values()))
    for cfg, ids in id_sets.items():
        if ids != reference_ids:
            only_ref = reference_ids - ids
            only_cfg = ids - reference_ids
            raise ValueError(
                f"Question ID mismatch between reference and {cfg}: "
                f"{len(only_ref)} missing in {cfg}, {len(only_cfg)} extra.\n"
                f"Example missing: {next(iter(only_ref)) if only_ref else '—'}"
            )

    first_cfg = next(iter(config_rows))
    ordered_ids = [r["id"] for r in config_rows[first_cfg]]

    data: dict[str, dict[str, np.ndarray]] = {}
    for cfg, idx in indexed.items():
        data[cfg] = {
            metric: np.array([float(idx[qid][metric]) for qid in ordered_ids])
            for metric in metrics
            if metric in next(iter(idx.values()))
        }
    return data


def _fmt_ci(lo: float, hi: float) -> str:
    return f"[{lo:+.4f}, {hi:+.4f}]"


def write_full_report(
    result,
    data: dict[str, dict[str, np.ndarray]],
    faith_cis: dict[str, tuple[float, float, float]],  # config -> (est, lo, hi)
    out_path: Path,
) -> None:
    """Write reports/full_comparison.md."""
    lines: list[str] = []
    a = lines.append

    a("# Four-configuration comparison: base · rag · ft · ft_rag")
    a("")
    a("*Generated by `scripts/run_stats.py` — numbers come from logged MLflow runs.*")
    a("")
    a(f"**N = {result.bootstrap[0].n}** questions (frozen eval set, `EXPERIMENT.md` §4).")
    a("")
    a("## Per-configuration results (B=10,000, seed=42)")
    a("")
    a("| Config | EM point est. | EM 95% CI | F1 point est. | F1 95% CI |")
    a("|---|---|---|---|---|")
    for cfg in CONFIGS:
        b_em = next(
            (b for b in result.bootstrap if b.config == cfg and b.metric == "exact_match"),
            None,
        )
        b_f1 = next(
            (b for b in result.bootstrap if b.config == cfg and b.metric == "token_f1"),
            None,
        )
        em_str = (
            f"{b_em.point_estimate:.4f} | [{b_em.ci_lower:.4f}, {b_em.ci_upper:.4f}]"
            if b_em
            else "— | —"
        )
        f1_str = (
            f"{b_f1.point_estimate:.4f} | [{b_f1.ci_lower:.4f}, {b_f1.ci_upper:.4f}]"
            if b_f1
            else "— | —"
        )
        a(f"| {cfg} | {em_str} | {f1_str} |")

    if faith_cis:
        a("")
        a("### RAG-config faithfulness (bootstrap 95% CI)")
        a("")
        a("| Config | Faithfulness est. | 95% CI |")
        a("|---|---|---|")
        for cfg, (est, lo, hi) in faith_cis.items():
            a(f"| {cfg} | {est:.4f} | [{lo:.4f}, {hi:.4f}] |")

    a("")
    a("## Pairwise contrasts — all five C1–C5 (Holm-adjusted α=0.05)")
    a("")
    a("Holm–Bonferroni is applied jointly across all five pre-registered contrasts within")
    a("each metric. A contrast is significant if the adjusted p-value < 0.05.")
    a("")
    a("| # | Contrast | Metric | Δ (mean diff) | 95% CI on Δ | Test | p (raw) | p (adj) | Sig? |")
    a("|---|---|---|---|---|---|---|---|---|")
    contrast_labels = {
        ("base", "rag"): "C1",
        ("base", "ft"): "C2",
        ("base", "ft_rag"): "C3",
        ("ft", "ft_rag"): "C4",
        ("rag", "ft_rag"): "C5",
    }
    for pw in result.pairwise:
        label = contrast_labels.get((pw.config_a, pw.config_b), "—")
        contrast_str = f"{pw.config_a} vs {pw.config_b}"
        metric_str = pw.metric.replace("_", " ")
        ci_str = _fmt_ci(pw.diff_ci_lower, pw.diff_ci_upper)
        sig = "✓ Yes" if pw.significant else "✗ No"
        p_raw = f"{pw.p_value_raw:.4f}" if pw.p_value_raw >= 0.0001 else "<0.0001"
        p_adj = f"{pw.p_value_adjusted:.4f}" if pw.p_value_adjusted >= 0.0001 else "<0.0001"
        a(
            f"| {label} | {contrast_str} | {metric_str} "
            f"| {pw.mean_difference:+.4f} | {ci_str} "
            f"| {pw.test} | {p_raw} | {p_adj} | {sig} |"
        )

    a("")
    a("## Statistical methodology")
    a("")
    a("- **N:** 300 questions (150 FinQA test + 150 TAT-QA dev).")
    a(
        "- **Bootstrap CIs:** B=10,000 paired resamples of question indices (seed=42); percentile method; 95% CI."
    )
    a("- **McNemar exact test:** applied to binary Exact Match outcomes per contrast.")
    a(
        "- **Paired permutation test:** sign-flip on per-question F1 differences; B=10,000 permutations."
    )
    a(
        "- **Multiple-comparison correction:** Holm–Bonferroni across all five C1–C5 contrasts jointly within each metric."
    )
    a("- **Forest plots:** `reports/forest_C1.png` through `reports/forest_C5.png`.")
    a("")
    a("## Interpretation")
    a("")
    # Collect significant contrasts
    sig_pairs = [
        (pw.config_a, pw.config_b, pw.metric, pw.mean_difference)
        for pw in result.pairwise
        if pw.significant
    ]
    if sig_pairs:
        a(
            f"After Holm–Bonferroni correction across all five pre-registered contrasts, "
            f"{len(sig_pairs)} contrast–metric combination(s) are significant at α=0.05:"
        )
        a("")
        for ca, cb, metric, delta in sig_pairs:
            label = contrast_labels.get((ca, cb), "—")
            pw = next(
                p
                for p in result.pairwise
                if p.config_a == ca and p.config_b == cb and p.metric == metric
            )
            a(
                f"- **{label} ({ca} vs {cb}, {metric.replace('_', ' ')}):** "
                f"Δ={delta:+.4f}, 95% CI [{pw.diff_ci_lower:+.4f}, {pw.diff_ci_upper:+.4f}], "
                f"{pw.test}, p_adj={pw.p_value_adjusted:.4f}"
            )
    else:
        a("No contrasts reach significance after Holm–Bonferroni correction at α=0.05.")

    out_path.write_text("\n".join(lines) + "\n")
    logger.info("Report written → %s", out_path)


def main() -> None:
    paths = {cfg: Path(f"reports/{cfg}_results.jsonl") for cfg in CONFIGS}
    for cfg, p in paths.items():
        if not p.exists():
            logger.error(
                "Missing artifact: %s — run scripts/run_eval.py --config configs/%s.yaml first",
                p,
                cfg,
            )
            sys.exit(1)

    logger.info("Loading results …")
    config_rows: dict[str, list[dict]] = {cfg: load_jsonl(p) for cfg, p in paths.items()}
    for cfg, rows in config_rows.items():
        logger.info("  %s: %d rows", cfg, len(rows))

    logger.info("Aligning %d configs by question ID …", len(CONFIGS))
    data = align_all(config_rows, metrics=METRICS)
    n = len(next(iter(data.values()))["exact_match"])
    logger.info("Aligned %d questions.", n)

    logger.info("Running statistical analysis — all 5 contrasts, B=10,000, seed=42 …")
    result = analyse(
        data,
        contrasts=CONTRASTS,
        metrics=METRICS,
        b=10_000,
        seed=42,
        alpha=0.05,
    )

    # Faithfulness bootstrap CI for RAG configs (no pairwise test — diagnostics only)
    faith_cis: dict[str, tuple[float, float, float]] = {}
    for cfg in RAG_CONFIGS:
        rows = config_rows[cfg]
        if all("faithfulness" in r for r in rows):
            scores = np.array([float(r["faithfulness"]) for r in rows])
            faith_result = analyse(
                {cfg: {"faithfulness": scores}},
                contrasts=[],
                metrics=["faithfulness"],
                b=10_000,
                seed=42,
                alpha=0.05,
            )
            fb = faith_result.bootstrap[0]
            faith_cis[cfg] = (fb.point_estimate, fb.ci_lower, fb.ci_upper)
            logger.info("%s faithfulness: %.4f [%.4f, %.4f]", cfg, *faith_cis[cfg])

    # Print summary
    print("\n" + "=" * 70)
    print("  FOUR-CONFIG COMPARISON — Statistical Summary")
    print("=" * 70)
    for pw in result.pairwise:
        sig = "SIG" if pw.significant else "n.s."
        print(
            f"  {pw.config_a:8s} vs {pw.config_b:8s}  {pw.metric:12s}"
            f"  Δ={pw.mean_difference:+.4f}  p_adj={pw.p_value_adjusted:.4f}  {sig}"
        )
    print("=" * 70 + "\n")

    # Forest plots — one per contrast
    contrast_labels = {
        ("base", "rag"): ("C1", "rag − base"),
        ("base", "ft"): ("C2", "ft − base"),
        ("base", "ft_rag"): ("C3", "ft_rag − base"),
        ("ft", "ft_rag"): ("C4", "ft_rag − ft"),
        ("rag", "ft_rag"): ("C5", "ft_rag − rag"),
    }
    for (ca, cb), (label, title) in contrast_labels.items():
        fig_path = Path(f"reports/forest_{label}.png")
        logger.info("Writing forest plot %s → %s", label, fig_path)
        forest_plot(result, config_a=ca, config_b=cb, out_path=fig_path, title=title)

    # Keep backward-compatible base_vs_rag report (C1) using the joint Holm result.
    fig_c1 = Path("reports/base_vs_rag_forest.png")
    forest_plot(result, config_a="base", config_b="rag", out_path=fig_c1, title="rag − base (C1)")
    write_report(
        result,
        config_a="base",
        config_b="rag",
        out_path=Path("reports/base_vs_rag.md"),
        figure_path=fig_c1,
        extra_context=(
            "_Note: p-values in this report are Holm-adjusted jointly across all five "
            "pre-registered contrasts C1–C5. The C1 result reported here may therefore "
            "differ from the Phase 3 report where only C1 was included in the correction._\n\n"
            "See `reports/full_comparison.md` for the complete four-configuration analysis."
        ),
    )

    # Main Phase 4 report
    write_full_report(
        result,
        data=data,
        faith_cis=faith_cis,
        out_path=Path("reports/full_comparison.md"),
    )

    logger.info(
        "Done.\n  Commit: reports/full_comparison.md  reports/forest_C*.png  reports/base_vs_rag.md"
    )


if __name__ == "__main__":
    main()
